"""real_name field

Revision ID: 16aa10346ca2
Revises: a8ea546a14eb
Create Date: 2020-05-16 21:23:07.762941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16aa10346ca2'
down_revision = 'a8ea546a14eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lang', sa.Column('real_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_lang_real_name'), 'lang', ['real_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lang_real_name'), table_name='lang')
    op.drop_column('lang', 'real_name')
    # ### end Alembic commands ###
