"""lang table

Revision ID: 51bf0bcf214d
Revises: 
Create Date: 2020-05-12 21:02:14.397482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bf0bcf214d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('stargazers', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lang_name'), 'lang', ['name'], unique=True)
    op.create_index(op.f('ix_lang_stargazers'), 'lang', ['stargazers'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lang_stargazers'), table_name='lang')
    op.drop_index(op.f('ix_lang_name'), table_name='lang')
    op.drop_table('lang')
    # ### end Alembic commands ###
