"""add timestamp field

Revision ID: a8ea546a14eb
Revises: 51bf0bcf214d
Create Date: 2020-05-12 21:56:38.621291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ea546a14eb'
down_revision = '51bf0bcf214d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lang', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_lang_timestamp'), 'lang', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lang_timestamp'), table_name='lang')
    op.drop_column('lang', 'timestamp')
    # ### end Alembic commands ###
